### ISSUE TITLE
jgmenu-apps sorts entries wrong in localized languages

### ISSUE THREAD

**Issue by m4vnel** [jgmenu/jgmenu#184]
Lets say we have two files, `foo.desktop` and `bar.desktop`, with this entries in the names fields ("ca" is locale for my system, "catalan"):

`foo.desktop:`
```
Name=foo
Name[ca]=afoo
```

`bar.desktop:`

```
Name=bar
Name[ca]=zbar
```

In the localized versions, the program `foo` should go first in sorting (`afoo` before `zbar`), but jgmenu shows `bar `before, i.e. does the sorting with the original values, not the localized.

I've tried some changes in `csv_name_format`, changing the order of `%n` and `%g`, with no efect. I've read too the i18n docs, but as far as I understand them are unrelated with this problem.

This behavior is the same in all the .desktop files. I have them in the standard path `/usr/share/applications`

**Comment by emdicmanel** [comment]
Great!
