### ISSUE TITLE
"no closing triple quote" message

### ISSUE THREAD

**Issue by emdicmanel** [jgmenu/jgmenu#185]
Example file `foo.txt`, with a filename containing commas:

```
filename1,xdg_open filename1
"""filename,2""",xdg_open """filename,2"""
```
When doing, for example,
`cat foo.txt | jgmenu --simple`

output is "no closing triple quote".

But all this options work well:

```
"""filename2""","""filename2"""
"""filename,2""","""filename,2"""
"""filename,2""",xdg_open """filename2"""
```
A bug, perhaps?

**Comment by emdicmanel** [comment]
Ouch. I've found that `"""filename,2""","""xdg_open filename,2"""` works. No bug at all.
Sorry and closing,

**Comment by johanmalm** [comment]
That's good. It's good when issues resolve themselves - so to speak :smile:
