### ISSUE TITLE
New release - 4.4.1 ?

### ISSUE THREAD

**Issue by napcok** [jgmenu/jgmenu#186]
Hello,
Is a new version planned to be released soon?
I see some nice improvements are ready: entries sorting, symlinked icons for example.

I am asking because I would like these improvements to be included in the new version of Mabox, which will be released in a few weeks.
Regards :)

**Comment by johanmalm** [comment]
Done :smile:
Thanks for prompt.
https://github.com/jgmenu/jgmenu/releases/tag/v4.4.1
