### ISSUE TITLE
[Request] any way to pin favourite apps, and possibly have a restart/shutdown button?

### ISSUE THREAD

**Issue by webodan** [jgmenu/jgmenu#190]
Title, it would be really nice if jgmenu could either show the most run apps at the topmost section of the menu (like rofi does) and possibly, to pin your favourites on its own section. Sorry if somebody asked for this before, I've been trying to change my theme outside of col3 (i ended up customizing this one as best I could) but I saw nothing in the documentation telling you how to change it.

Other than that, thank you for finally making tint2 really usable, I really missed a menu in openbox+tint2.

**Comment by johanmalm** [comment]
Showing most used apps at the top is quite intrusive for a tool as versatile as `jgmenu`. It would also take refactoring + significant testing. Happy to consider well-designed patches for this, but it is out-of-scope for me.

You can add your own favorites using prepend.csv / append.csv or by using widgets. See jgmenu-tutorial(7).

Glad you like it. Yes, it very much started off as the menu for tint2 :smile:
