### ISSUE TITLE
Not an issue, but kudos!

### ISSUE THREAD

**Issue by lobaluna** [jgmenu/jgmenu#191]
This is a project which is way too much under rated. And it is fantastic! I use it everyday with Mabox (Manjaro with Openbox magic). The developer of Mabox has done a remarkable work putting jgmenu to work. It is so friendly and beautiful.

I thank you warmly for this project of yours. Kudos!!! Three times kudos!

**Comment by johanmalm** [comment]
Thanks for the kind words. Much appreciated :smile;
