### ISSUE TITLE
A .desktop does not show up in jgmenu

### ISSUE THREAD

**Issue by PPC-scripts** [jgmenu/jgmenu#192]
Hi!
I'm "bugging" you again because I recently noticed a problem, while using jgmenu- it fails to show a certain .desktop file!
I'm attaching it, hoping that you can fix that easily, or, at least, point me to the solution of this strange situation!

Once again, thanks for this wonderful piece of software!
[live-usb-maker-gui-antix.desktop.tar.gz](https://github.com/jgmenu/jgmenu/files/10571082/live-usb-maker-gui-antix.desktop.tar.gz)

EDIT: I found the reason - I'm using a system localized in pt-pt. Jgmenu refuses to show  .desktop files containing commas in the fields "GenericName" or "GenericName[language_code]"
ex: 
GenericName[pt]=Criar um sistema operativo, com todas as funcionalidades, num dispositivo USB

If I edit out the commas, the menu entry instantly shows up (note: this .desktop file belongs to antiX Linux)

**Comment by johanmalm** [comment]
Thanks for tracking down the problem. We ought to fix that really!

**Comment by johanmalm** [comment]
https://github.com/jgmenu/jgmenu/pull/193

This should fix it. Are you in a position to build + test?

**Comment by PPC-scripts** [comment]
Sorry for the delay - I'm having computer problems at my home PC and I'm
running from a live-pendrive - not the ideal to try building. But I'll try
to do so.
Meanwhile, I just noticed another problem- related to .desktop names.
I noticed, while testing what was causing the  bug I reported, that some
jgmenu entries are repeated: first the orignal one, with icon, that runs
the application, the second, just the name of the application, that does
not run anything.
This only happens if I'm showing "all apps", not in categories.
This seems to be caused bye having "Add" in the name of the application-
strange, I know.

You can try replicating this creating a .desktop file like this:
[Desktop Entry]
Name=Add

Open jgmenu showing all apps, and the menu entry "add" should come up twice.

Should I report this bug also, on your github?

P.


Johan Malm ***@***.***> escreveu no dia sexta, 3/02/2023 à(s)
21:46:

**Comment by PPC-scripts** [comment]
Correction:
Name=ad [...]
or
Name=Ad [...]

seem to trigger this, in the "all apps" menu mode

**Comment by PPC-scripts** [comment]
I kept testing:

Strangely the same thing as above happens in Names (or localized Names)
that start with "Ac"

Paulo P ***@***.***> escreveu no dia segunda, 6/02/2023 à(s)
15:16:

**Comment by johanmalm** [comment]
I can't reproduce the Add/Ad/Ac thing. It might be related to the original issue. Suggest we solve one thing at the time and then I'll help you fault find.

Regarding the first issue with the comma in the generic name... take the following steps (no need to install)

```
git clone --branch=names-with-comma https://github.com/jgmenu/jgmenu
cd jgmenu
./configure
make
./jgmenu-apps | ./jgmenu --simple
```

If you're on Debian, you can use this script to get the dev packages installed `./scripts/install-debian-dependencies.sh`

**Comment by PPC-scripts** [comment]
Yes! This seems to fix all the bugs that  I reported, when I run

./jgmenu-apps | ./jgmenu --simple

Many thanks for the short tutorial!

P.


Johan Malm ***@***.***> escreveu no dia segunda, 6/02/2023
à(s) 17:18:

**Comment by PPC-scripts** [comment]
Note: however, running: 


./jgmenu-apps | ./jgmenu 

Shows my default menu configuration, with the "bug"

**Comment by johanmalm** [comment]
> Note: however, running:
> 
> ./jgmenu-apps | ./jgmenu
> 
> Shows my default menu configuration, with the "bug"

Yes, that's because `./jgmenu` without `--simple` does not read from `stdin` to it relies on the `jgmenu-apps` module installed on your system (which doesn't contain the fix).
