### ISSUE TITLE
Search filter widget bugs the heck out when inputting certain characters

### ISSUE THREAD

**Issue by 45jqlakjrf87ayte7hy34ter4nguijauzl4eitk** [jgmenu/jgmenu#194]
`@search` display is broken after inputting characters interpreted by pango or whatever.

Less than.
> pango_layout_set_markup_with_accel: Error on line 1 char 12: “<” is not a valid name

Ampersand.
>pango_layout_set_markup_with_accel: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as \&amp;

**Comment by johanmalm** [comment]
Guess we should escape those characters here https://github.com/jgmenu/jgmenu/blob/87994d1b8c195bae2be438f68019d92ceea2d656/src/widgets.c#L112

**Comment by johanmalm** [comment]
Should work now. Thanks for raising.
