### ISSUE TITLE
Consider SVG support optional

### ISSUE THREAD

**Issue by vaygr** [jgmenu/jgmenu#195]
Since librsvg2 introduced a Rust dependency that requires a heavy toolchain, I was wondering if you could consider SVG support as optional to keep jgmenu light on dependencies for those who don't need it and/or compact distributions.

edit: I was able to build jgmenu without linking with librsvg2, so I could probably work on a PR.

**Comment by johanmalm** [comment]
Is there a distribution that does not package librsvg2?
I’m guessing rust is only a build dependency for librsvg2, so you should need to have the rust tool chain installed to build jgmenu.

**Comment by johanmalm** [comment]
If I take `librsvg2` out of the Makefile I get the following:

```
     CC    jgmenu.o
In file included from src/jgmenu.c:27:
src/x11-ui.h:10:10: fatal error: librsvg/rsvg.h: No such file or directory
   10 | #include <librsvg/rsvg.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:76: jgmenu.o] Error 1
```

I generally prefer not to `#ifdef` the code much, but if you've got a good use-case for it, I'm happy to accept a patch.

**Comment by johnraff** [comment]
On Debian Bullseye librsvg2-2 and librsvg2-common have no rust dependencies, so it looks like an issue only for the builder, not for users.

**Comment by johanmalm** [comment]
^ Yep.

GTK3/4 depend on librsvg2 too. As do `rofi`, `openbox`, etc. Like @johnraff said - that doesn't mean you need rust installed to build these packages. The `jgmenu` dependencies were carefully chosen to fit within the intended eco-system. 

Having said all that, @vaygr if you're building a minimalist OS without GTK etc then I'm happy to accept `#ifdef` patches (and help think through how we might do it).

Personally I want to spend my time on `labwc` and don't want to get side-tracked writing patches for rare use-cases (but happy to advise/test/merge).

**Comment by johnraff** [comment]
To be clear, I said rust was not needed to install or use the librsvg packages. I haven't tested what the build requirements are.

**Comment by vaygr** [comment]
@johanmalm thanks! I opened #196 for you to take a look.
