### ISSUE TITLE
How to Make a Jgmenu custom theme like neon

### ISSUE THREAD

**Issue by subhaniminhas** [jgmenu/jgmenu#197]
I could not find any config file or reference on internet on how to make custom menu theme for jgmenu. I need to make multiple themes, closely resembling outlook of Windows 10 and 11 for PakOS Linux, and like jgmenu to be the one solution which can do it. Please help.

**Comment by johanmalm** [comment]
The only way to theme is to create a `~/.config/jgmenu/jgmenurc`

Try something like

```
menu_width          = 272
menu_padding_top    = 10
menu_padding_right  = 10
menu_padding_bottom = 10
menu_padding_left   = 10
menu_valign         = bottom
item_radius         = 2
item_border         = 1
font		    = Roboto Condensed 9
color_menu_bg       = #cecece 90
color_menu_border   = #888888 100
color_norm_fg       = #444444 100
color_sel_bg        = #e6e6e6 100
color_sel_fg        = #444444 100
color_sel_border    = #888888 100
```

**Comment by subhaniminhas** [comment]
Well , I have been learning jgmenu for a few days, and thanks for creating such a powerful yet seemingly simple way. Although I must say documentation is not fully readable at times. 
I only hop than once I am done with my sample menus for PakOS 12, I will let you know, so that you can add their screen shots at jgmenu as well 😀

**Comment by johanmalm** [comment]
That’s great.
Suggestions for documentation improvements gratefully received.
