### ISSUE TITLE
Non responding Menu Items in Debain 12, with Lxqt and jgmenu v4.4.1

### ISSUE THREAD

**Issue by subhaniminhas** [jgmenu/jgmenu#198]
I am trying to develop a Windows 11 Themed Menu for PakOS 12, which is based on Debian 12 (RC2, as of now) I added a few text and icons in prepend.csv, and added custom commands with them, however, after that addition, main icons have stopped working to mouse click events while keyboard navigation works well.  Additionally, once i click on an icon, instead of triggering its main action, either one thew custom button actions are triggered. 
I am attaching contents of the jgmenu folder so that if it a bug, it may be reported, and if i am making a mistake, you may kindly help by looking  at config files, if you have some spare time. 

Thanks a lot for your earlier, quicker response about jgmenu themes.  If this bug is resolved, i intend to link the contents of my documents below the menu place holder, as in case of windows 11. Thus making this theme almost fully compatible with Windows 11 menu.  
Also i intend to make a startup script to help adjust jgmenu size (Windows size, font size, icon size, spacing etc) based on  screen resolution. 

on further testing i found that even built in themes like neon with prepend elements have the same issue. looks like a version based bug. Any suggestions will be welcome. 

[win11.tar.gz](https://github.com/jgmenu/jgmenu/files/11470162/win11.tar.gz)

**Comment by johanmalm** [comment]
The `win11.tar.gz` appears to be empty.

Could you just post your `prepend.csv` file in the chat here (preferably as a code section).

**Comment by subhaniminhas** [comment]
prepend.csv: 

# Search box
@rect,,23,10,550,35,3,left,top,#111111 90,#000000 2,
@search,,55,11,545,30,3,left,top,auto ,#000000 0,Type here to search
@icon,,30,20,20,20,3,left,top, , ,/home/pakuser/.config/jgmenu/search.png

#Leave Dialogue
#@icon, lxqt-leave ,500,540,50,50,25,left,top,#000000 00, #000000 00,/home/pakuser/.local/share/icons/fluent11/64x64/apps/system-shutdown.svg
@icon, lxqt-leave ,500,540,34,34,25,left,top,#000000 00, #000000 00,/home/pakuser/.config/jgmenu/logout.png

#User Avatar
@icon,lxqt-leave --logout,23,540,38,38,26,left,top,,,/home/pakuser/.config/jgmenu/face.png  
@text,,90,530,200,60,2,left,top,#e6e6e6 100,#000000 50,pakuser


jgmenurc:
tint2_look           = 0
columns              = 2
menu_width           = 600
menu_height_min      = 600
menu_height_max      = 600
menu_padding_top     = 50
menu_padding_right   = 40
menu_padding_bottom  = 270
menu_padding_left    = 40
menu_radius          = 10
menu_border          = 0
menu_halign          = center
menu_valign          = bottom
item_margin_y        = 5
item_height          = 50
item_padding_x       = 8
item_radius          = 0
item_border          = 2
sep_height           = 5
font                 = UbuntuMono 12
icon_size            = 48
icon_text_spacing    = 3
color_menu_bg        = #2B303B 80
color_norm_bg        = #1C2023 0
color_norm_fg        = #ffffff 80
color_sel_bg         = #8fa1b3 0
color_sel_fg         = #ffffff 80
color_sel_border     = #111111 80
color_sep_fg         = #919BA0 40
#csv_single_window = 1
#csv_no_duplicates = 1
csv_no_dirs = 1
csv_name_format = %n \n%g

**Comment by subhaniminhas** [comment]
i cloned the git, and installed the latest jgmenu using 
sudo make install 
now jgmenu v4.4.1-6-g9501 is installed into the system, although it will be some effort to install teh latest version into an iso using build and make , as i havbe never tried it, so any suggestion is welcome. 
everything  is ok, all issues have resolved including wrong touch areas ,
only, all icons are now missing (in menus, using any of the built in themes, or custom themes) . 

Any suggestions on how to resolve old error, or this new issue.

**Comment by johanmalm** [comment]
Try removing `~/.cache/jgmenu` and run again.

Try setting `icon_theme=Papirus` (or whatever) in `jgmenurc`

Regarding building deb packages, I'm a bit out of touch on that. 
- There is a `debian/` folder in the jgmenu project top directory (https://github.com/jgmenu/jgmenu/tree/master/debian)
- This might be helpful: https://github.com/jgmenu/jgmenu/blob/master/scripts/make-debian.sh
- I haven't used debian for some time, but think the following might be it: `debuild -us -uc`

**Comment by subhaniminhas** [comment]
removing ~/.cache/jgmenu had no effect, however once i set icon_theme to exact address, which in my case is 
icon_theme= /usr/share/icons/Papirus
some icons show, any many dont including xscreensaver entries  While this was true earlier in lxqt, its more noticeable, since many applications like games have lost their icons now. 
As for xscreensaver entries being shown in menu, Their .desktop file clearly has 
OnlyShowIn=MATE; 
entry, any idea how to exclude such applications from showing up in lxqt jgmenu? 
Overall many of the issues have resolved , but still end result is not good enough to start work on improving this theme for PakOS 12. Please help, i would love to include it in my next build.

**Comment by subhaniminhas** [comment]
Sir, just to request, too many icons are missing in the compiled version, and the normal version in debian 12 is pretty broken. I hope the next build will resolve the icon issue, so I can try to develope my long list of menus based on that. Please do inform once next build has the issue resolved. 
Happy Coding
