### ISSUE TITLE
rare error connection "could" ber established to monitor due missing tools or artifacts

### ISSUE THREAD

**Issue by mckaygerhard** [jgmenu/jgmenu#207]
in minimalistic desktops instalations i got something.

sometimes when i recomiple i got this rare error so i tried into a virtual machine 

![image](https://github.com/jgmenu/jgmenu/assets/1571724/aab1dd49-6d95-4e92-9ec5-516a0894e703)

i catch the fmessage at x11-ui on line 229 

https://github.com/jgmenu/jgmenu/blob/e054785677c0b9296d64294181bac7ed762d0e4d/src/x11-ui.c#L228C3-L228C3

### confusion

so the first here is the confused message :

`connection could be established to monitor` 

must be 

`connection cannot be established to monitor, inconsistent information or missing tools`

### why?

`xrandr` must be installed (`x11-xserver-utils `in devuan by example or `xrandr` on alpine)
`mesa-utils` must be installed 

EDIT: i removed and reset and confirmed

**Comment by johanmalm** [comment]
Thanks. Great feedback. Will do a patch.
