### ISSUE TITLE
How to open menu without anything in focus?

### ISSUE THREAD

**Issue by Animeshz** [jgmenu/jgmenu#209]
Seems like first item except `@search` and `@icon` gets highlighted and is in focus when jgmenu is launched.

I'd like it not to be in focus by default, so that clicking anywhere on screen wouldn't launch that application. Or atleast force focus on to search bar instead of clickable item.

Thanks!

**Comment by johanmalm** [comment]
Good point. I think this would be more consistent with most other menus.

Someone on ArchLabs asked for the same a while ago.

Have cooked up a quick patch, but it could do with some testing. Fancy trying it before I merge it?

[patch.txt](https://github.com/jgmenu/jgmenu/files/13403381/patch.txt)

**Comment by Animeshz** [comment]
Hey thanks for the quick reply, and yes this patch works perfectly fine for me :smiley:

![out](https://github.com/jgmenu/jgmenu/assets/26714676/0d3f517b-88f5-4155-9687-61ef69313537)

**Comment by johanmalm** [comment]
Okay. I'd better do some testing under an X11 WM before merging it. Have only tested under XWayland so far, so might have missed something obvious. 

Grateful for any further testing you can carry out to make sure it doesn't introduce any regressions.

Nice scrot by the way.

**Comment by johanmalm** [comment]
What icon theme is it?

**Comment by Animeshz** [comment]
> Grateful for any further testing you can carry out to make sure it doesn't introduce any regressions.

Sure I'll keep using the patch for the next week.



> What icon theme is it?

Its papirus theme :)

**Comment by napcok** [comment]
I always considered focused first item as a good and needed feature. :( One less action needed to do stuff. Searching does not need focus anyway.
