### ISSUE TITLE
Variable font sizes for csv texts

### ISSUE THREAD

**Issue by clemencyworld1** [jgmenu/jgmenu#224]
Thanks again for this wonderful software. So, i want to make some of the texts bigger than the others in my prepend.csv. From a tutorial which i can't find the source now, you can style texts by adding html tags to it i.e <b>text</b> makes the text bold. How can i apply such syntax on my text to make it larger. If it's not yet implemented, may i humbly make it a feature request.
Thanks

**Comment by napcok** [comment]
![Mabox_20240709-15-51-07](https://github.com/jgmenu/jgmenu/assets/3028270/548828f6-b4fb-443c-99ca-3b1addc7371f)

**Comment by johanmalm** [comment]
@napcok Thanks for responding so quickly.

Ref: `sep_markup` at https://jgmenu.github.io/jgmenu.1.html

**Comment by clemencyworld1** [comment]
Thanks a lot for this
