### ISSUE TITLE
Is it feasible to use them in order of frequency of use?

### ISSUE THREAD

**Issue by kopfhanger** [jgmenu/jgmenu#226]
Is it possible for jgmenu's app launch menu to sort apps by how often they are used? I didn't find the corresponding setting syntax in jgmenurc.

**Comment by johanmalm** [comment]
Technically yes, but it wouldn't be trivial.

If anyone is willing to roll their sleeves up and come up with some implementation ideas + write some code for it, I'll help. I'd prefer if it didn't add too much complexity.

I'm guessing it would require:

1. A record (possibly in `~/.cache/jgmenu/`) to be amended every time an application is executed from jgmenu. That bit should be easy.
2. Either (a) the menu-generators (like `jgmenu-apps`) to parse said record to order the files according to usage or (b) `jgmenu` itself to sort in accordance with usage. Either way it's likely to need some configuration options - as a bare minimum to enable/disable it, but possibly also to handle situations where there are submenus and pipemenus.

In a simpler application that just shows a list of applications, I imagine this would be quite trivial, but it's likely to get tricky with a flexible tool like `jgmenu`.

**Comment by kopfhanger** [comment]
Thanks for answering. Since there's no ready-made syntax for setting it, forget it. The solution you propose is very clear, but I don't have enough programming skills to solve it now.
