### ISSUE TITLE
Cursor disappears when using jgmenu with kitty

### ISSUE THREAD

**Issue by nonotran68** [jgmenu/jgmenu#231]
Hi,

I recently noticed a minor bug when running jgmenu with the Kitty terminal. The issue occurs when the cursor moves into the kitty terminal area, it suddenly disappears.

https://github.com/user-attachments/assets/426af490-83cd-444f-bdd1-affac27f3f73

https://github.com/user-attachments/assets/264fc866-35c6-4387-b4fa-d65d69ed25e1

<details>
<summary><b>Here is my config:</b></summary>

```
position_mode = pointer
stay_alive = 0
tint2_look = 0
terminal_exec = alacritty
terminal_args = -e
menu_width = 160
menu_padding_top = 5
menu_padding_right = 5
menu_padding_bottom = 5
menu_padding_left = 5
menu_radius = 8
menu_border = 0
menu_halign = left
sub_hover_action = 1
item_margin_y = 5
item_height = 30
item_padding_x = 8
item_radius = 6
item_border = 0
sep_height = 2
font = Clarity City Bold 12px
icon_size = 16
icon_theme = Papirus-Dark
arrow_string = 󰄾
color_menu_border = #ffffff 0
color_menu_bg = #1a1b26
color_norm_bg = #ffffff 0
color_norm_fg = #c0caf5
color_sel_bg = #222330
color_sel_fg = #c0caf5
color_sep_fg = #414868
```
</details>

```bash
jgmenu --version
jgmenu v4.4.1

type jgmenu       
jgmenu is /sbin/jgmenu
```

My laptop is currently running on Arch Linux and using `bspwm` as window manager and `picom` as compositor.

Thank you for looking into this. I really appreciate your time and support!

**Comment by johanmalm** [comment]
Thanks for reporting. I first tried under Wayland and interestingly, the cursor does not disappear there.
Anyway, I can reproduce on X.Org Server.
I tried with rofi which uses similar technology and get the same result, so I suspect it's a shortcoming with `kitty`. Would you mind exploring with them?

**Comment by nonotran68** [comment]
Thank you for the quick response. I also noticed that this is only an issue with kitty, while everything works fine with other terminals emulator. I will create an issue on the kitty repository.
