### ISSUE TITLE
All Applications,^checkout(apps)

### ISSUE THREAD

**Issue by majestic78** [jgmenu/jgmenu#239]
Hi. How to properly launch this prepend.csv:
All Applications,^checkout(apps),utilities
^sep()
^tag(apps)
It works when launched via jgmenu_run or simply jgmenu, but if I want to directly specify prepend.csv and launch it using jgmenu --csv-file=~/.config/jgmenu/prepend.csv, then hovering the mouse cursor over "All Applications" does not trigger the dropdown menu with program categories.

**Comment by johanmalm** [comment]
Have answered on the bunsenlabs thread.
